feat: `List.insertP` and lemmas
leanprover-community/batteries pull request #569
Opened 2024-01-30 07:24 UTC by fgdorais

This is a generalized, tail-recursive version of the insert step in insertion-sort:
```lean
def insertionSort [LE α] [DecidableRel (α:=α) (· ≤ ·)] (l : List α) := 
  l.foldl (fun s a => s.insertP (. ≤ a) a) [] -- fully tail recursive and stable!
```
It will be useful to streamline and optimize `ac_rfl` once moved to Std.

PS: Perhaps someone has a better name?

2024-01-30 07:31 UTC, digama0 commented on Std/Data/List/Basic.lean
> +the list if `p` never fails on `l`.
Before reading the docs, my initial guess was that the polarity of `p` would be flipped, and it inserts `a` before the first element for which `p` is true. This seems more consistent with `findP` et al.

2024-02-05 18:37 UTC, joehendrix requested changes
I don't have a specific objection to `insertP`, but we are working on triaging what parts of Std can and should be moved to Lean core (with further polishing) to provide a good new user experience.

As such I'd like to hold off introducing new operations unless they enhance existing capabilities or are needed for high-priority tactics.

2024-02-17 17:36 UTC, fgdorais commented
The `ac_rfl` move has been canceled so there is no immediate need for this. It's still a useful addition so I'm reluctant to close but closing might be better than rotting.

2024-08-17 00:25 UTC, digama0 commented on Batteries/Data/List/Lemmas.lean
> +  | cons _ _ ih => split <;> simp [insertP_loop, ih]
```suggestion
  | cons _ _ ih => split <;> simp [insertP_loop, ih]

```

2024-08-17 00:27 UTC, merged